//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Capa_Entidad;
    
    public partial class PROYECTO_FINAL_P2Entities : DbContext
    {
        public PROYECTO_FINAL_P2Entities()
            : base("name=PROYECTO_FINAL_P2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DOCUMENTO> DOCUMENTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int Codigo_Documentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Codigo_Documentos");
        }
    
        public virtual ObjectResult<REPORTE_USUARIOS_Result> REPORTE_USUARIOS(string nOMBRE)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REPORTE_USUARIOS_Result>("REPORTE_USUARIOS", nOMBREParameter);
        }
    
        public virtual ObjectResult<REPORTE_DEPARTAMENTOS_Result> REPORTE_DEPARTAMENTOS(string dEPARTAMENTO)
        {
            var dEPARTAMENTOParameter = dEPARTAMENTO != null ?
                new ObjectParameter("DEPARTAMENTO", dEPARTAMENTO) :
                new ObjectParameter("DEPARTAMENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REPORTE_DEPARTAMENTOS_Result>("REPORTE_DEPARTAMENTOS", dEPARTAMENTOParameter);
        }
    
        public virtual ObjectResult<REPORTE_TODO_LOS_DOCUMENTOS_Result> REPORTE_TODO_LOS_DOCUMENTOS(Nullable<int> documentos)
        {
            var documentosParameter = documentos.HasValue ?
                new ObjectParameter("Documentos", documentos) :
                new ObjectParameter("Documentos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REPORTE_TODO_LOS_DOCUMENTOS_Result>("REPORTE_TODO_LOS_DOCUMENTOS", documentosParameter);
        }
    
        public virtual ObjectResult<REPORTE_EMPLEADOS_Result> REPORTE_EMPLEADOS(Nullable<int> uSUAR)
        {
            var uSUARParameter = uSUAR.HasValue ?
                new ObjectParameter("USUAR", uSUAR) :
                new ObjectParameter("USUAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REPORTE_EMPLEADOS_Result>("REPORTE_EMPLEADOS", uSUARParameter);
        }
    
        public virtual ObjectResult<REPORTE_ORIGEN_POR_DEPARTAMENTO_Result> REPORTE_ORIGEN_POR_DEPARTAMENTO(string dEPT)
        {
            var dEPTParameter = dEPT != null ?
                new ObjectParameter("DEPT", dEPT) :
                new ObjectParameter("DEPT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REPORTE_ORIGEN_POR_DEPARTAMENTO_Result>("REPORTE_ORIGEN_POR_DEPARTAMENTO", dEPTParameter);
        }
    
        public virtual ObjectResult<REPORTE_DEPARTAMENTO_DESTINO_Result> REPORTE_DEPARTAMENTO_DESTINO(string dEPT)
        {
            var dEPTParameter = dEPT != null ?
                new ObjectParameter("DEPT", dEPT) :
                new ObjectParameter("DEPT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REPORTE_DEPARTAMENTO_DESTINO_Result>("REPORTE_DEPARTAMENTO_DESTINO", dEPTParameter);
        }
    
        public virtual ObjectResult<REPORTE_RANGO_FECHA_Result> REPORTE_RANGO_FECHA(string yEARSTART, string yEARFINISH)
        {
            var yEARSTARTParameter = yEARSTART != null ?
                new ObjectParameter("YEARSTART", yEARSTART) :
                new ObjectParameter("YEARSTART", typeof(string));
    
            var yEARFINISHParameter = yEARFINISH != null ?
                new ObjectParameter("YEARFINISH", yEARFINISH) :
                new ObjectParameter("YEARFINISH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REPORTE_RANGO_FECHA_Result>("REPORTE_RANGO_FECHA", yEARSTARTParameter, yEARFINISHParameter);
        }
    }
}
